### ISSUE TITLE
How about integrating React-Admin

### ISSUE THREAD

**Issue by santoshgistto** [chaoming/fireact#1]
How about integrating `React-Admin`?
Ref: https://github.com/marmelab/react-admin

**Comment by chaoming** [comment]
I have gone through its documentation. `React-Admin` doesn't seem to be a good fit solution for building an SaaS front-end. I could be wrong as I don't know it very well.

Key concerns are:
- Flexibility on the authentication methods.
- Role based structure is for one account. It doesn't work with the scenario that the same user might have different permission level in different projects
- The data provider is designed to work with one back end only. There is workaround to use multiple back ends but that increase the complexity.

Overall it's a good solution if you need an UI on top of one back end that the users won't create their own projects within the system, but that's not suitable for most SaaS.
