### ISSUE TITLE
invoices collection is not created on the account

### ISSUE THREAD

**Issue by ParthibHW19** [chaoming/fireact#10]
Bellow webhook code is not getting invoked...  my webhook url is  https://<domain>/stripeWebHook, is this correct?
![webhook code](https://user-images.githubusercontent.com/72288965/112924008-ebce4e00-9141-11eb-94f6-9301d5f280c9.PNG)

**Comment by chaoming** [comment]
The web hook URL should look like this `https://firebse-location-project-id.cloudfunctions.net/stripeWebHook` based on your Firebase project.

Please read the **Create Stripe Webhook** section in the installation document https://chaoming.github.io/fireact/installation.html

**Comment by ParthibHW19** [comment]
I have selected project id from firebase project settings , and replaced web hook url with https://<project_id>.cloudfunctions.net/stripeWebHook,  I get web hook failed in Stripe logs.
Is the webhook url I put is correct?.
![invoice_created_failed](https://user-images.githubusercontent.com/72288965/112944347-47f69980-9165-11eb-9b45-7621fa37a818.PNG)

**Comment by ParthibHW19** [comment]
Thank you. I have updated the webhook url with firebase location , project id , webhook is success. but still could not see invoices generated in accounts collection, hence unable to see on the billing page.
![invoice_created_successfully](https://user-images.githubusercontent.com/72288965/112949111-6fe8fb80-916b-11eb-8f33-8e54ec0593bc.PNG)

**Comment by ParthibHW19** [comment]
Thank you. it is working fine.
