### ISSUE TITLE
How to add credit card details with name and address?

### ISSUE THREAD

**Issue by ParthibHW19** [chaoming/fireact#11]
Hi Chaoming Li,

Thanks a lot for the Fireact project. It saves lot of time in implementing e2e SaaS app. One question, while selecting subscription and make credit card payment, it asks only credit card number, but I need to also show name and address also as shown in the attachment. Is it possible to include this change in fireact?.

![credit card details](https://user-images.githubusercontent.com/72288965/113097491-8ce40400-9229-11eb-8d94-6cc59a13f37e.PNG)

**Comment by chaoming** [comment]
Currently, Fireact doesn't support additional details for the payment, but it's in the roadmap.

The plan is to be able to collect billing details and apply tax.

**Comment by ParthibHW19** [comment]
Fine. Thank you.
