### ISSUE TITLE
mailgun configuration

### ISSUE THREAD

**Issue by ParthibHW19** [chaoming/fireact#14]
I have setup custom domain in Mailgun .and it is working fine in Postman.
But if I use the same configuration in the mailgun.json, and testing the user invite function, it is not working.
Is there any other parameter should i add in the mailgun.json file?

"api_key": "<my private api key",
    "domain": "https://api.mailgun.net/v3/my custom domain/messages",
    "site_name": "my custom domain",
    "from": "mailgun@my custom domain",
    "invite_url": "https://my custom domain/invite"

**Comment by chaoming** [comment]
The `domain` setting doesn't look right. The value you have is an URL. I think that should be the domain you register in the Mailgun system.

**Comment by ParthibHW19** [comment]
Thank. you. It is working now after replacing with domain instead of url.

**Comment by ParthibHW19** [comment]
Thank you.
