### ISSUE TITLE
Getting CORS error from cloudfunction

### ISSUE THREAD

**Issue by dominicdev** [chaoming/fireact#16]
need help any idea? or i missed setupng from firebase, testing it in local build, happens in adding account name

**Comment by chaoming** [comment]
Check the logs in cloud function. It's likely that there is some internal error if you missed a step or have a wrong configuration.

**Comment by DmitryUlyanov** [comment]
I had this problem, it turned out not to be related to CORS at all. In my case my firebase GCP project was located in europe, while cloud functions were deployed to `us-west1`. To change region do this in `functions/index.js`:
```
const functions = require('firebase-functions').region("europe-west2");
```
and in `src/components/FirebaseAuth/firebase.js` : 
```
const CloudFunctions = FirebaseAuth.functions("europe-west2");
```
