### ISSUE TITLE
Anyone using an M1 Mac to build/deploy?

### ISSUE THREAD

**Issue by WooffyDave** [chaoming/fireact#17]
Hello.  This product looks great to save time on what I'm attempting to build.  It's also my first React project, so sorry if these are common issues.

I'm working with an M1 iMac and I can't 'build install' without errors.  Doing things one at a time, it looks like it's the Stripe stuff causing problems.  I've tried installing node via brew both native and using Rosetta and I've even tried running the npm commands via Rosetta.  I can attach the error messages if it'll help (once I get back to that machine).  I'm just curious if anyone else here is working with an M1 Mac and had problems and how you got around them.  I can get to an Intel Mac later today I can try on, but I'd love to be able to work on the iMac if possible.  Thanks.

**Comment by chaoming** [comment]
What errors you get?

**Comment by WooffyDave** [comment]
After attempting to read the logs and understand them, looks like it was a node-sass issue.  I updated the package.json to point to 6.0.0 instead of 5.0.0 and it builds now.

Everything looks good now.  Apologies for filing an issue before understanding what it was.  (Like I said, first time using React, sorry).

**Comment by chaoming** [comment]
No worries. I will close this issue.
