### ISSUE TITLE
coreui error

### ISSUE THREAD

**Issue by ParthibHW19** [chaoming/fireact#22]
Hi,

Since this morning , getting this error, how to fix it?..

![core ui error](https://user-images.githubusercontent.com/72288965/124410281-b8bcdb80-dd7c-11eb-9437-2eaae6809b51.PNG)

**Comment by ParthibHW19** [comment]
Even your demo app : https://fireact-e1bdc.firebaseapp.com/ , 
also throwing above error. Is there any major updates to coreui library?.

**Comment by chaoming** [comment]
Looks like the CoreUI hosted JS is updated to 4.0. Need to find a copy of the older version and replace it.

**Comment by chaoming** [comment]
The issue has been fixed by including CoreUI 3.4.0 files in the project, instead of using the hosted version.
