### ISSUE TITLE
Issue with deployment

### ISSUE THREAD

**Issue by wowan90** [chaoming/fireact#25]
I followed all the steps in the documentation. I get following screen (as well if I run the project locally)

![image](https://user-images.githubusercontent.com/29895028/125959136-1d936714-91db-448e-8b45-cb7cbc39fc9c.png)

Any idea?

**Comment by chaoming** [comment]
Looks like you are using the Firebase `serve` command. Try `npm start` and access `localhost:3000`.

**Comment by wowan90** [comment]
Hello Chaoming,

thanks for your reply.. I could finally fix the problem. It was the same issue with the build/public folder like already mentioned before.

Now I run into the next issue. Once the login page is loaded.. and i try to login i get following screen and the page is not continueing loading..

![image](https://user-images.githubusercontent.com/29895028/126024931-164044e6-563b-4d7c-9a69-2aed70a740b8.png)

Here is also the live linke for my deployment on firebase. https://contentbot-saas.web.app/

Any idea? Thanks in advance.

**Comment by chaoming** [comment]
Have you deployed the firebase rules and the cloud functions? You need both to make it work on the server side.

**Comment by wowan90** [comment]
Yes I did,

Firebase rules!

![image](https://user-images.githubusercontent.com/29895028/126065243-40b6cee0-41be-4ab6-9c09-5553aa09fc64.png)

Webhooks:

![image](https://user-images.githubusercontent.com/29895028/126065548-ee1b178e-b91b-4f3b-a8fd-a0707b937a34.png)

Webhooks - Firebase - Functions

Plans:

![image](https://user-images.githubusercontent.com/29895028/126065791-9bbd7af0-7a9a-4b8d-861c-dd1af62d3de3.png)

I did everything step by step.

**Comment by chaoming** [comment]
The domain in your screenshot and the domain in the error message don't match. Are they the same project?

**Comment by chaoming** [comment]
The error says the firestore rules deny access to the database.

**Comment by chaoming** [comment]
Have a similar issue last week. It turns out that's related to the antivirus software and the firewall. @wowan90 , maybe try to disable your antivirus and firewall to test the connection to Firestore?
