### ISSUE TITLE
No window.coreui object in browser when run locally

### ISSUE THREAD

**Issue by lnrssll** [chaoming/fireact#26]
For some reason, when running locally (using npm run start), the javascript for coreui (called from the <script> element in public/index.html) doesn't appear to be running, so there's no window.coreui object available in my console (so I'm throwing an error when trying to call Sidebar._sidebarInterface(element) in src/components/menus/AppMenu/index.js:8, see image attached). The hosted version on firebase works perfectly, however. Any idea why I wouldn't be able to load the coreui javascript locally or how to solve this?
Ps. very cool project, thanks for putting it together!
![image](https://user-images.githubusercontent.com/53909902/136865108-cc75ac5c-3a00-4bb5-b09d-c26e9b2704ab.png)

**Comment by lnrssll** [comment]
Yes, the coreui.bundle.min.js file is in my public folder and called in the index.html--in general, the entire repo is copied exactly as shown in the latest version. As someone commented (which appears to be deleted or something), it looks like the React component may be loading before the coreui js is parsed when I run in the dev build on localhost. I saw the issue about compatibility with newer versions of coreui (and the necessity of importing coreui as it is done by including the file) so I thought you might know a workaround to ensure the header script loads in time.

**Comment by chaoming** [comment]
The project has been migrated to Material-UI
