### ISSUE TITLE
Do we need to add Stripe idempotency key?

### ISSUE THREAD

**Issue by jeffreydavis83** [chaoming/fireact#9]
Not an issue actually, I just want to ask if we need to add [idempotency key](https://stripe.com/docs/api/idempotent_requests?lang=node) to avoid multiple card charge incidents.

**Comment by chaoming** [comment]
I don't think it's needed.

Fireact creates subscriptions instead of charges, and the charges are automated by Stripe based on the subscription product pricing.

**Comment by jeffreydavis83** [comment]
Makes sense. Also, can you please guide me briefly how can we handle 3D secure cards in Fireact?

**Comment by chaoming** [comment]
Sorry, no experience with 3D secure cards.
